FROM ubuntu:22.04

EXPOSE 3000

ENV CI=0
ENV DOCKER=1
ENV GEM_PATH=/gems
ENV BUNDLE_PATH=/bundle
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Chicago
ENV RAILS_ENV=development
ENV RAILS_LOG_TO_STDOUT=true
ENV SECRET_KEY_BASE=whateverdoesntmatter

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    imagemagick \
    libmagic-dev \
    libpq-dev \
    libreoffice \
    libssl-dev \
    libyaml-dev \
    poppler-utils \
    shared-mime-info \
    zip \
    zlib1g-dev

# ImageMagick 6 ships with support for PDF and similar formats disabled in
# the security policy. Disable that.
RUN sed -i '/disable ghostscript format types/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="PS"/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="PS2"/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="PS3"/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="EPS"/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="PDF"/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="XPS"/d' /etc/ImageMagick-6/policy.xml

# Install Ruby
RUN git clone https://github.com/rbenv/ruby-build.git \
    && PREFIX=/usr/local ./ruby-build/install.sh \
    && ruby-build -v 3.2.2 /usr/local

# This is a host volume.
WORKDIR /app

COPY Gemfile /tmp
COPY Gemfile.lock /tmp
RUN cd /tmp \
    && gem install bundler \
    && bundle install \
    && cd /app

# Everything else has to be done in the entry command because /app will be
# empty until we launch via docker compose.