FROM ubuntu:22.04

ENV CI=1
ENV DOCKER=0
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Chicago
ENV RAILS_ENV=test
ENV RAILS_LOG_TO_STDOUT=true
ENV SECRET_KEY_BASE=whateverdoesntmatter

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    imagemagick \
    libmagic-dev \
    libpq-dev \
    libssl-dev \
    libyaml-dev \
    poppler-utils \
    shared-mime-info \
    zip \
    zlib1g-dev

# Install Ruby
RUN git clone https://github.com/rbenv/ruby-build.git \
    && PREFIX=/usr/local ./ruby-build/install.sh \
    && ruby-build -v 3.2.2 /usr/local

RUN mkdir app
WORKDIR app

# Copy the main application, except whatever is listed in .dockerignore.
COPY . ./

RUN cp config/credentials/ci.yml config/credentials/test.yml

RUN gem install bundler \
    && bundle config path vendor/bundle \
    && bundle config set without 'development production' \
    && bundle install --jobs 4 --retry 5
