FROM ubuntu:22.04

ENV CI=1
ENV DOCKER=0
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Chicago
ENV RAILS_ENV=test
ENV RAILS_LOG_TO_STDOUT=true
ENV SECRET_KEY_BASE=whateverdoesntmatter

# python-is-python3 is needed to compile libv8
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    imagemagick \
    libmagic-dev \
    libpq-dev \
    libreoffice \
    libssl-dev \
    libyaml-dev \
    poppler-utils \
    python-is-python3 \
    shared-mime-info \
    unzip \
    zip \
    zlib1g-dev

# ImageMagick 6 ships with support for PDF and similar formats disabled in
# the security policy. Disable that.
RUN sed -i '/disable ghostscript format types/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="PS"/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="PS2"/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="PS3"/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="EPS"/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="PDF"/d' /etc/ImageMagick-6/policy.xml \
    && sed -i '/policy domain="coder" rights="none" pattern="XPS"/d' /etc/ImageMagick-6/policy.xml

# Install Ruby
RUN git clone https://github.com/rbenv/ruby-build.git \
    && PREFIX=/usr/local ./ruby-build/install.sh \
    && ruby-build -v 3.2.2 /usr/local

RUN mkdir app
WORKDIR app

# Copy the main application, except whatever is listed in .dockerignore.
COPY . ./

RUN cp config/credentials/ci.yml config/credentials/test.yml

RUN gem install bundler \
    && bundle config path vendor/bundle \
    && bundle config set without 'development production' \
    && bundle install --jobs 4 --retry 5
