FROM ubuntu:21.10

EXPOSE 3000

ENV CI=0
ENV DOCKER=1
ENV GEM_PATH=/gems
ENV BUNDLE_PATH=/bundle
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Chicago
ENV RAILS_ENV=development
ENV RAILS_LOG_TO_STDOUT=true
ENV SECRET_KEY_BASE=whateverdoesntmatter

RUN apt-get update && apt-get install -y \
    build-essential \
    libmagic-dev \
    libpq-dev \
    libssl-dev \
    zlib1g-dev \
    libvips-tools \
    curl \
    git \
    shared-mime-info

# Install Ruby
RUN git clone https://github.com/rbenv/ruby-build.git \
    && PREFIX=/usr/local ./ruby-build/install.sh \
    && ruby-build -v 3.1.2 /usr/local

# This is a host volume.
WORKDIR /app

COPY Gemfile /tmp
COPY Gemfile.lock /tmp
RUN cd /tmp \
    && gem install bundler \
    && bundle install \
    && cd /app

# Everything else has to be done in the entry command because /app will be
# empty until we launch via docker compose.