Rails.application.routes.draw do

  resources :items
  resources :handles
  resources :units
  resources :users, except: [:create, :delete]
  resources :collections, except: :index
  resources :registered_elements, param: :name, path: 'elements'

  root 'welcome#index'
  get '/', to: 'welcome#index'
  get '/dashboard', to: 'welcome#dashboard'
  get '/deposit', to: "welcome#deposit"

  # authentication routes
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/login', to: 'sessions#new', as: :login, via: [:get, :post]
  match '/logout', to: 'sessions#destroy', as: :logout, via: :all
  match '/auth/failure', to: 'sessions#unauthorized', as: :unauthorized, via: [:get, :post]

  # handle routing
  get '/handle/:prefix/:suffix', to: 'handles#resolve'

  # resources
  resources :identities do
    collection do
      get 'login'
      get 'register'
    end
  end
  resources :invitees
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]

  # catch unknown routes, but ignore datatables and progress-job routes, which are generated by engines.
  match "/*a" => "errors#error404", :constraints => lambda{|req| req.path !~/progress-job/ && req.path !~ /datatables/ }, via: [ :get, :post, :patch, :delete ]

end
