##
# Dictionary of controlled vocabularies used in the submission interface.
# These have been extracted from DSpace's input-form.xml. Access them using the
# Vocabulary class.
#

common_genres:
  name: Common Genres
  terms:
    - stored_value: article
      displayed_value: Article
    - stored_value: bibliography
      displayed_value: Bibliography
    - stored_value: book
      displayed_value: Book
    - stored_value: book chapter
      displayed_value: Book Chapter
    - stored_value: book review
      displayed_value: Book Review
    - stored_value: editorial
      displayed_value: Editorial
    - stored_value: essay
      displayed_value: Essay
    - stored_value: conference paper
      displayed_value: Conference Paper / Presentation
    - stored_value: conference poster
      displayed_value: Conference Poster
    - stored_value: conference proceeding
      displayed_value: Conference Proceeding (whole)
    - stored_value: data
      displayed_value: Data
    - stored_value: dissertation/thesis
      displayed_value: Dissertation / Thesis
    - stored_value: drawing
      displayed_value: Drawing
    - stored_value: fiction
      displayed_value: Fiction
    - stored_value: journal
      displayed_value: Journal (whole)
    - stored_value: newsletter
      displayed_value: Newsletter
    - stored_value: performance
      displayed_value: Performance
    - stored_value: photograph
      displayed_value: Photograph
    - stored_value: poetry
      displayed_value: Poetry
    - stored_value: presentation/lecture/speech
      displayed_value: Presentation / Lecture / Speech
    - stored_value: proposal
      displayed_value: Proposal
    - stored_value: oral history
      displayed_value: Oral history
    - stored_value: report
      displayed_value: Report (Grant or Annual)
    - stored_value: score
      displayed_value: Score
    - stored_value: technical report
      displayed_value: Technical Report
    - stored_value: website
      displayed_value: Website
    - stored_value: working paper
      displayed_value: Working / Discussion Paper
    - stored_value: other
      displayed_value: Other

common_iso_languages:
  name: Common ISO Languages
  terms:
    - stored_value: en
      displayed_value: English
    - stored_value: zh
      displayed_value: Chinese
    - stored_value: fr
      displayed_value: French
    - stored_value: de
      displayed_value: German
    - stored_value: it
      displayed_value: Italian
    - stored_value: ja
      displayed_value: Japanese
    - stored_value: es
      displayed_value: Spanish
    - stored_value: tr
      displayed_value: Turkish
    - stored_value: other
      displayed_value: Other

common_types:
  name: Common Types
  terms:
    - stored_value: sound
      displayed_value: Audio
    - stored_value: dataset
      displayed_value: Dataset / Spreadsheet
    - stored_value: still image
      displayed_value: Image
    - stored_value: text
      displayed_value: Text
    - stored_value: moving image
      displayed_value: Video
    - stored_value: other
      displayed_value: Other

degree_names:
  name: Degree Names
  terms:
    - stored_value: B.A. (bachelor's)
      displayed_value: B.A. (bachelor's)
    - stored_value: B.S. (bachelor's)
      displayed_value: B.S. (bachelor's)
    - stored_value: M.A. (master's)
      displayed_value: M.A. (master's)
    - stored_value: M.Arch. (master's)
      displayed_value: M.Arch. (master's)
    - stored_value: M.F.A. (master's)
      displayed_value: M.F.A. (master's)
    - stored_value: M.H.R.I.R. (master's)
      displayed_value: M.H.R.I.R. (master's)
    - stored_value: M.L.A. (master's)
      displayed_value: M.L.A. (master's)
    - stored_value: M.Mus. (master's)
      displayed_value: M.Mus. (master's)
    - stored_value: M.S. (master's)
      displayed_value: M.S. (master's)
    - stored_value: M.S.P.H. (master's)
      displayed_value: M.S.P.H. (master's)
    - stored_value: M.U.P. (master's)
      displayed_value: M.U.P. (master's)
    - stored_value: A.Mus.D. (doctoral)
      displayed_value: A.Mus.D. (doctoral)
    - stored_value: Au.D. (doctoral)
      displayed_value: Au.D. (doctoral)
    - stored_value: Ed.D. (doctoral)
      displayed_value: Ed.D. (doctoral)
    - stored_value: J.S.D. (doctoral)
      displayed_value: J.S.D. (doctoral)
    - stored_value: Ph.D. (doctoral)
      displayed_value: Ph.D. (doctoral)

dissertation_thesis:
  name: Dissertation Thesis
  terms:
    - stored_value: Dissertation
      displayed_value: Dissertation (Doctoral level only)
    - stored_value: Thesis
      displayed_value: Thesis (Bachelor's or Master's level)
