class AddIndexesOnFkColumns < ActiveRecord::Migration[7.0]
  def change
    add_index :ad_groups_user_groups, :ad_group_id
    add_index :ad_groups_user_groups, :user_group_id
    add_index :administrator_groups, :unit_id
    add_index :administrator_groups, :user_group_id
    add_index :affiliations_user_groups, :affiliation_id
    add_index :affiliations_user_groups, :user_group_id
    add_index :ascribed_elements, :item_id
    add_index :ascribed_elements, :registered_element_id
    add_index :bitstream_authorizations, :item_id
    add_index :bitstream_authorizations, :user_group_id
    add_index :bitstreams, :item_id
    add_index :collection_item_memberships, :collection_id
    add_index :collection_item_memberships, :item_id
    add_index :collections, :metadata_profile_id
    add_index :collections, :parent_id
    add_index :collections, :submission_profile_id
    add_index :departments, :user_group_id
    add_index :departments, :user_id
    add_index :embargoes, :item_id
    add_index :events, :bitstream_id
    add_index :events, :item_id
    add_index :events, :user_id
    add_index :handles, :collection_id
    add_index :handles, :item_id
    add_index :handles, :unit_id
    add_index :hosts, :user_group_id
    add_index :imports, :collection_id
    add_index :imports, :user_id
    add_index :invitees, :inviting_user_id
    add_index :items, :submitter_id
    add_index :local_identities, :invitee_id
    add_index :manager_groups, :collection_id
    add_index :manager_groups, :user_group_id
    add_index :messages, :bitstream_id
    add_index :metadata_profile_elements, :metadata_profile_id
    add_index :metadata_profile_elements, :registered_element_id
    add_index :metadata_profiles, :institution_id
    add_index :registered_elements, :institution_id
    add_index :submission_profile_elements, :registered_element_id
    add_index :submission_profile_elements, :submission_profile_id
    add_index :submission_profiles, :institution_id
    add_index :submitter_groups, :collection_id
    add_index :submitter_groups, :user_group_id
    add_index :submitters, :collection_id
    add_index :submitters, :user_id
    add_index :unit_collection_memberships, :collection_id
    add_index :unit_collection_memberships, :unit_id
    add_index :units, :institution_id
    add_index :units, :parent_id
    add_index :user_groups_users, :user_id
    add_index :user_groups_users, :user_group_id
    add_index :users, :affiliation_id
    add_index :users, :local_identity_id
  end
end
